/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SchedulesRouteImport } from './routes/schedules'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as ManagersRouteImport } from './routes/managers'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as DrilldownRouteImport } from './routes/drilldown'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as CateringRouteImport } from './routes/catering'
import { Route as CampsRouteImport } from './routes/camps'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulesRoute = SchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagersRoute = ManagersRouteImport.update({
  id: '/managers',
  path: '/managers',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const DrilldownRoute = DrilldownRouteImport.update({
  id: '/drilldown',
  path: '/drilldown',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const CateringRoute = CateringRouteImport.update({
  id: '/catering',
  path: '/catering',
  getParentRoute: () => rootRouteImport,
} as any)
const CampsRoute = CampsRouteImport.update({
  id: '/camps',
  path: '/camps',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/camps': typeof CampsRoute
  '/catering': typeof CateringRoute
  '/companies': typeof CompaniesRoute
  '/devices': typeof DevicesRoute
  '/drilldown': typeof DrilldownRoute
  '/employees': typeof EmployeesRoute
  '/forecast': typeof ForecastRoute
  '/managers': typeof ManagersRoute
  '/overview': typeof OverviewRoute
  '/projects': typeof ProjectsRoute
  '/reports': typeof ReportsRoute
  '/scanner': typeof ScannerRoute
  '/schedules': typeof SchedulesRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/camps': typeof CampsRoute
  '/catering': typeof CateringRoute
  '/companies': typeof CompaniesRoute
  '/devices': typeof DevicesRoute
  '/drilldown': typeof DrilldownRoute
  '/employees': typeof EmployeesRoute
  '/forecast': typeof ForecastRoute
  '/managers': typeof ManagersRoute
  '/overview': typeof OverviewRoute
  '/projects': typeof ProjectsRoute
  '/reports': typeof ReportsRoute
  '/scanner': typeof ScannerRoute
  '/schedules': typeof SchedulesRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/camps': typeof CampsRoute
  '/catering': typeof CateringRoute
  '/companies': typeof CompaniesRoute
  '/devices': typeof DevicesRoute
  '/drilldown': typeof DrilldownRoute
  '/employees': typeof EmployeesRoute
  '/forecast': typeof ForecastRoute
  '/managers': typeof ManagersRoute
  '/overview': typeof OverviewRoute
  '/projects': typeof ProjectsRoute
  '/reports': typeof ReportsRoute
  '/scanner': typeof ScannerRoute
  '/schedules': typeof SchedulesRoute
  '/users': typeof UsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/camps'
    | '/catering'
    | '/companies'
    | '/devices'
    | '/drilldown'
    | '/employees'
    | '/forecast'
    | '/managers'
    | '/overview'
    | '/projects'
    | '/reports'
    | '/scanner'
    | '/schedules'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/camps'
    | '/catering'
    | '/companies'
    | '/devices'
    | '/drilldown'
    | '/employees'
    | '/forecast'
    | '/managers'
    | '/overview'
    | '/projects'
    | '/reports'
    | '/scanner'
    | '/schedules'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/camps'
    | '/catering'
    | '/companies'
    | '/devices'
    | '/drilldown'
    | '/employees'
    | '/forecast'
    | '/managers'
    | '/overview'
    | '/projects'
    | '/reports'
    | '/scanner'
    | '/schedules'
    | '/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  CampsRoute: typeof CampsRoute
  CateringRoute: typeof CateringRoute
  CompaniesRoute: typeof CompaniesRoute
  DevicesRoute: typeof DevicesRoute
  DrilldownRoute: typeof DrilldownRoute
  EmployeesRoute: typeof EmployeesRoute
  ForecastRoute: typeof ForecastRoute
  ManagersRoute: typeof ManagersRoute
  OverviewRoute: typeof OverviewRoute
  ProjectsRoute: typeof ProjectsRoute
  ReportsRoute: typeof ReportsRoute
  ScannerRoute: typeof ScannerRoute
  SchedulesRoute: typeof SchedulesRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedules': {
      id: '/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof SchedulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/managers': {
      id: '/managers'
      path: '/managers'
      fullPath: '/managers'
      preLoaderRoute: typeof ManagersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drilldown': {
      id: '/drilldown'
      path: '/drilldown'
      fullPath: '/drilldown'
      preLoaderRoute: typeof DrilldownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catering': {
      id: '/catering'
      path: '/catering'
      fullPath: '/catering'
      preLoaderRoute: typeof CateringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camps': {
      id: '/camps'
      path: '/camps'
      fullPath: '/camps'
      preLoaderRoute: typeof CampsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  CampsRoute: CampsRoute,
  CateringRoute: CateringRoute,
  CompaniesRoute: CompaniesRoute,
  DevicesRoute: DevicesRoute,
  DrilldownRoute: DrilldownRoute,
  EmployeesRoute: EmployeesRoute,
  ForecastRoute: ForecastRoute,
  ManagersRoute: ManagersRoute,
  OverviewRoute: OverviewRoute,
  ProjectsRoute: ProjectsRoute,
  ReportsRoute: ReportsRoute,
  ScannerRoute: ScannerRoute,
  SchedulesRoute: SchedulesRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
